#size	xhot	yhot	Path to PNG image	delay
24	11	11	/home/dim/.cache/cursors/crosshair/crosshair_000.png	50
30	13	13	/home/dim/.cache/cursors/crosshair/crosshair_001.png	50
36	16	16	/home/dim/.cache/cursors/crosshair/crosshair_002.png	50
48	22	22	/home/dim/.cache/cursors/crosshair/crosshair_003.png	50
72	33	33	/home/dim/.cache/cursors/crosshair/crosshair_004.png	50
96	44	44	/home/dim/.cache/cursors/crosshair/crosshair_005.png	50
