#size	xhot	yhot	Path to PNG image	delay
24	3	1	/home/dim/.cache/cursors/left_ptr/default_000.png	50
30	3	1	/home/dim/.cache/cursors/left_ptr/default_001.png	50
36	4	1	/home/dim/.cache/cursors/left_ptr/default_002.png	50
48	6	2	/home/dim/.cache/cursors/left_ptr/default_003.png	50
72	9	3	/home/dim/.cache/cursors/left_ptr/default_004.png	50
96	12	4	/home/dim/.cache/cursors/left_ptr/default_005.png	50
