#size	xhot	yhot	Path to PNG image	delay
16	3	1	/home/dim/.cache/cursors/left_ptr/left_ptr_000.png	40
20	4	1	/home/dim/.cache/cursors/left_ptr/left_ptr_001.png	40
22	4	1	/home/dim/.cache/cursors/left_ptr/left_ptr_002.png	40
24	5	1	/home/dim/.cache/cursors/left_ptr/left_ptr_003.png	40
28	6	1	/home/dim/.cache/cursors/left_ptr/left_ptr_004.png	40
32	6	2	/home/dim/.cache/cursors/left_ptr/left_ptr_005.png	40
40	8	2	/home/dim/.cache/cursors/left_ptr/left_ptr_006.png	40
48	10	3	/home/dim/.cache/cursors/left_ptr/left_ptr_007.png	40
56	12	3	/home/dim/.cache/cursors/left_ptr/left_ptr_008.png	40
64	13	4	/home/dim/.cache/cursors/left_ptr/left_ptr_009.png	40
72	15	4	/home/dim/.cache/cursors/left_ptr/left_ptr_010.png	40
80	17	5	/home/dim/.cache/cursors/left_ptr/left_ptr_011.png	40
88	18	5	/home/dim/.cache/cursors/left_ptr/left_ptr_012.png	40
96	20	6	/home/dim/.cache/cursors/left_ptr/left_ptr_013.png	40
