#size	xhot	yhot	Path to PNG image	delay
24	7	5	/home/dim/.cache/cursors/hand2/pointer_000.png	50
30	8	6	/home/dim/.cache/cursors/hand2/pointer_001.png	50
36	10	7	/home/dim/.cache/cursors/hand2/pointer_002.png	50
48	14	10	/home/dim/.cache/cursors/hand2/pointer_003.png	50
72	21	15	/home/dim/.cache/cursors/hand2/pointer_004.png	50
96	28	20	/home/dim/.cache/cursors/hand2/pointer_005.png	50
