#size	xhot	yhot	Path to PNG image	delay
24	16	16	/home/dim/.cache/cursors/crosshair/crosshair_000.png	50
30	20	20	/home/dim/.cache/cursors/crosshair/crosshair_001.png	50
36	24	24	/home/dim/.cache/cursors/crosshair/crosshair_002.png	50
48	32	32	/home/dim/.cache/cursors/crosshair/crosshair_003.png	50
