#size	xhot	yhot	Path to PNG image	delay
24	4	4	/home/dim/.cache/cursors/left_ptr/default_000.png	50
30	5	5	/home/dim/.cache/cursors/left_ptr/default_001.png	50
36	6	6	/home/dim/.cache/cursors/left_ptr/default_002.png	50
48	8	8	/home/dim/.cache/cursors/left_ptr/default_003.png	50
